services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - learn-by-doing_44692f_airflow
      
  # metabase:
  #   image: metabase/metabase:v0.46.6.4
  #   volumes:
  #     - ./include/metabase-data:/metabase-data
  #   environment:
  #     - MB_DB_FILE=/metabase-data/metabase.db
  #   ports:
  #     - 3000:3000
  #   restart: always

volumes:
  db-data:

networks:
  learn-by-doing_44692f_airflow:
    driver: bridge